### ISSUE TITLE
Matches without deck are still tracked (as None)

### ISSUE THREAD

**Issue by culinko** [Epix37/Hearthstone-Deck-Tracker#1005]
I found out if you have have selected no deck and play any mode, the matches are still tracked as None, even though I've selected to Record stats only for Ranked, Arena and Casual. Also it's interesting that Sapphiron and Thaurissan have class icons because they played only the cards from that specific class. The games will get cleared once you restart the tracker.

log: http://pastebin.com/raw.php?i=p0c3uQUa

![ai matches](https://cloud.githubusercontent.com/assets/11700272/7902586/792878c0-07be-11e5-959a-3776302195c2.png)

**Comment by culinko** [comment]
So, this is still happening in the newest version (0.10.9). How to reproduce: Use no deck, play Innkeeper + Adventure bosses. Then refresh the stats by clicking on different filters. This does not happen if you use a deck. Record Practice is still unchecked.

Also, I've found that if you check the Practice recording and you use a deck, the tracker won't save any of the Adventure games (probably because they are listed as mode "None"). Innkeeper games are saved, same goes for all AI games (Innkeeper + Adventure) if you have no deck selected.

**Comment by culinko** [comment]
This is happening for all modes, not just Practice/Spectate.

**Comment by riQQ** [comment]
This is fixed by now (see https://github.com/Epix37/Hearthstone-Deck-Tracker/blob/master/Hearthstone%20Deck%20Tracker/GameEventHandler.cs#L691-L694).

**Comment by culinko** [comment]
This still happens in the newest test version. Unchecked recording for Practice, restarted both HDT and Hearthstone (just in case) and the match was still tracked with game mode "None".
![none](https://cloud.githubusercontent.com/assets/11700272/11560023/c1127096-99bd-11e5-88d8-fcd3070bf757.png)

**Comment by riQQ** [comment]
I checked and for me stats aren't recorded vs The Innkeeper with no deck used. In my options only Record for Ranked and Arena are checked. I'm using a version compiled from the latest commit.

**Comment by culinko** [comment]
Actually, I also have recording "Other" checked. Let me try to reproduce one more time without it.

**Comment by riQQ** [comment]
Recording Other does record games with game mode `None` (see https://github.com/Epix37/Hearthstone-Deck-Tracker/blob/master/Hearthstone%20Deck%20Tracker/GameEventHandler.cs#L48).

**Comment by culinko** [comment]
I unchecked it, restarted both HS and HDT and it still happens. I am playing with no deck and the only checked game modes are Ranked, Casual and Arena. Right after I concede vs AI, i go to the stats, then click on ranked filter and back to All (to refresh the stats). The Practice game is still there (as None).

**Comment by riQQ** [comment]
Okay, I didn't know I had to refresh. The games are added to the stats page, but are gone after restarting.

**Comment by culinko** [comment]
Yeah, I know that the games are cleared after the restart. But I would like them to not be there at all. I guess this should be reopened then.

**Comment by riQQ** [comment]
You're right, this has to be reopened. I'm looking into it.

**Comment by Epix37** [comment]
Working on it right now :).

**Comment by culinko** [comment]
This happened again vs an adventure boss (Skelesaurus Hex). Using version 0.13.7.Attaching logs: http://s000.tinyupload.com/index.php?file_id=05187478452066627704

![adventure](https://cloud.githubusercontent.com/assets/11700272/12012285/2be43466-acee-11e5-8a99-874570757be9.png)
