### ISSUE TITLE
Export is Broken

### ISSUE THREAD

**Issue by Mikhayil** [Epix37/Hearthstone-Deck-Tracker#1322]
When exporting a deck from HDT 1 card is always left out for some reason so that there is only 29 cards and this is usually random, sorry if this has already been posted.

**Comment by MechaLynx** [comment]
See if anything [here](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#exporting) fixes it.

**Comment by Mikhayil** [comment]
Oh. I fixed it myself by experimenting a little. It seems if i put it on fast deck exporting then my client loads too slow for it to register all the clicks :p

**Comment by MechaLynx** [comment]
Nice. Please close this issue unless you still have the problem. You can re-open it later if the problem re-appears and you can't find a solution from the FAQ. I would do it myself but this isn't my repository.
