### ISSUE TITLE
Timer is not stopped after match end, it keeps counting

### ISSUE THREAD

**Issue by Cu8eR** [Epix37/Hearthstone-Deck-Tracker#1705]
Timer is not stopped after match end, it keeps counting

**Comment by Epix37** [comment]
Is this consistent? Fixed by restarting HDT? Please provide more information.

**Comment by Cu8eR** [comment]
No, it is not fixed when I restart my HDT. Just finish the match, do not click anywhere and check your timer - it is counting

**Comment by Epix37** [comment]
Ah, so you mean when you stay in the game after it ends, before you are back in menu?

**Comment by Cu8eR** [comment]
Yes! Exactly... it should be stopped automaticaly
