### ISSUE TITLE
"Close with Hearthstone" does not work

### ISSUE THREAD

**Issue by CrendKing** [Epix37/Hearthstone-Deck-Tracker#1921]
Because of https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/1857 , I thought it would be convenient to let HDT close itself before the bug triggers. Looks like that option does not work. I made sure HDT recognizes the running Hearthstone before closing the game.

HDT version: 0.13.7

**Comment by misnor** [comment]
Do you have any plugins attached to HDT? I pulled HDT down and set it to close with HS and it closes for me - is there any more details you can provide to narrow this down?

**Comment by CrendKing** [comment]
I do not have any plugin enabled. Both issue 1857 and this issue are reproducible reliably. It is possible that a certain combination of config causes these. I attach the relevant files here.

[Hearthstone Deck Tracker.zip](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/72863/Hearthstone.Deck.Tracker.zip)

**Comment by misnor** [comment]
I'm able to reproduce your issue with your config.xml.

A temporary fix may be unselecting "Use Advanced Search"  under Options-> Tracker -> Settings - can you confirm if this works for you?

**Comment by CrendKing** [comment]
Good finding. This change fixes both this issue and issue #1857. Because of that, there is no point for me to use this option anymore. Guess there is some bug related to that Advanced window search.

**Comment by misnor** [comment]
PR https://github.com/Epix37/Hearthstone-Deck-Tracker/pull/1931 should fix this issue in a future release.

**Comment by CrendKing** [comment]
Looks like you mixed hard tabs with soft tabs in that pull request, but thanks for the fix so quickly.

**Comment by misnor** [comment]
Thanks for pointing that out, should be fixed now!

**Comment by Nicte** [comment]
Hi,

Just to let you know that I still see this issue. I have tried the proposed fix of unselecting "Advance Windows Search" but it didn't help.

![image](https://cloud.githubusercontent.com/assets/4835465/13727717/01829522-e8fe-11e5-8161-8e44cc24bc2f.png)
