### ISSUE TITLE
Bad tracking since last update (0.7.0)

### ISSUE THREAD

**Issue by mvy** [Epix37/Hearthstone-Deck-Tracker#501]
Hi,

Since I updated the tracker, it seems to be buggy. What I have experienced is: 

- works fine on IA games
- Does not reset when playing ranked (card still green, or greyed out at start of the game)
- Ranked games are not recorded anymore

Is it my side? Should I clear some cache or something? I already rebooted both HS and the tracker with no better result.

**Comment by ToonBoon** [comment]
Same thing here, also sometimes the game thinks I have cards still in hand that I've played turns ago.

**Comment by Epix37** [comment]
should be fixed now with v0.7.1

**Comment by mvy** [comment]
Bug still there. Here is a screenshot of the thing:

![Bug 501](http://i.imgur.com/CEy0VVV.png)

**Comment by Epix37** [comment]
Please try the verison linked in #511 (the second one)
