### ISSUE TITLE
Opponent's drawn cards don't clear between matches

### ISSUE THREAD

**Issue by alexhuijsman** [Epix37/Hearthstone-Deck-Tracker#511]
I am having to restart the program between matches since updating today.

The opponent's cards on the left side of the screen no longer resets when i start a new match
![capture](https://cloud.githubusercontent.com/assets/8128930/5607055/e111f7f6-93fe-11e4-8b39-5564ab0c7902.PNG)

**Comment by renj0806** [comment]
Same thing happens to me. Have to restart the program to reset.

**Comment by askarmuk** [comment]
Same here. Used version 0.7.0.
![bandicam 2015-01-04 22-40-40-165](https://cloud.githubusercontent.com/assets/8628595/5607061/2de45aa2-946c-11e4-8192-f9dc9c4bbd9f.jpg)

**Comment by Epix37** [comment]
Still a problem with v0.7.1?

**Comment by alexhuijsman** [comment]
Yes, still a problem with 0.7.1

**Comment by renj0806** [comment]
Yup, I am currently using v0.7.1

**Comment by Epix37** [comment]
Let me know if this version fixes the problem: http://www.mediafire.com/download/arhwmip8i84j7d0/Hearthstone_Deck_Tracker-v0.7.2_gameendfixmaybe.zip

**Comment by alexhuijsman** [comment]
With this version, when a new match starts, the opponent's card list is
completely missing, including the % stats. Thanks for being so quick to
respond!

**Comment by Epix37** [comment]
Well that's progress at least. This one might do the trick then: http://www.mediafire.com/download/33e9tjhw46lp43h/Hearthstone_Deck_Tracker-v0.7.2_gameendfixmaybe2.zip

**Comment by ToonBoon** [comment]
Issue persists, though card markers now do show up properly which was a problem if I remember correctly. Though that may have only been an 0.7.0 issue

**Comment by ToonBoon** [comment]
Another thing that may or may not be related is that I have noticed cards popping up in the list way before the game tells me it's my turn.

**Comment by Epix37** [comment]
that's just how the new log reader works, that's fine.

**Comment by alexhuijsman** [comment]
I've played three matches in a row and it all seems to be working again with the http://www.mediafire.com/download/33e9tjhw46lp43h/Hearthstone_Deck_Tracker-v0.7.2_gameendfixmaybe2.zip version.

Thank you sir! Should I close this issue now?

**Comment by Epix37** [comment]
That sounds promising. Leave it open for now, I'll close it with v0.7.2 release

**Comment by ToonBoon** [comment]
Using this version my deck became invisible

http://i.imgur.com/UBTc5rA.png
http://pastebin.com/nX7QfPTC

**Comment by Epix37** [comment]
@ToonBoon try deleting (renaming) the config.xml in "%appdata%/HearthstoneDeckTracker" (options > other > tracker > open appdata folder)

**Comment by surasshu** [comment]
I got the issue of my own hand not being reset after a game, and its still (somewhat?) persisting for 7.2 for me! I don't know if there's a thing I can send in to help out here?

**Comment by alexhuijsman** [comment]
Oh dear, it appears that I am experiencing "the opponent's card list is
completely missing, including the % stats" on new matches sometimes, but not all the time. I'm not sure what the cause may be. Will report back if I notice any patterns.

**Comment by alexhuijsman** [comment]
Okay, I figured it out, actually. I am using the option "hide leftmost cards when friendslist is open". If I open my friendslist and then click anywhere on the screen to close it, the UI stays hidden. If i click near the friendslist again, the UI comes back.

**Comment by Epix37** [comment]
Try checking the "Force ON" option.

**Comment by mvy** [comment]
Problem of #501 and #511 persists with that version. I tried renaming the `config.xml` but no better results.

Ranked games still do not record. I'm stuck with the last Warlock game I played on 7.0. Nothing has been added since then.

**Comment by alexhuijsman** [comment]
Thanks. Donation incoming!

**Comment by Epix37** [comment]
I have one more idea for tonight: http://www.mediafire.com/download/il57674kelpr4ky/Hearthstone_Deck_Tracker-v0.7.2_gameendfixmaybe3.zip

Now I'm heading to bed though. If that doesn't work either.. hopefully I can find the problem tomorrow. Everything working fine on my end makes this pretty difficult.

**Comment by hyperbolist** [comment]
0.7.2 solved the problem of the opponent deck overlay not resetting in a new match, and the timer overlay not hiding/resetting between matches.

But my player deck still does not reset when I start a new match with 0.7.2.

My workaround is to switch to HearthstoneDeckTracker, select a different deck, then select the deck I'm playing.  This resets my deck in the overlay.

**Comment by killjoyX** [comment]
I am having the same problem, and no fixmaybes have helped, I've tried them all.  I have begun using hyperbolist's workaround and it does help, but a new version with the deck overlay resetting after each match would sure be appreciated.  Thanks, Killjoy

**Comment by mvy** [comment]
Ok, I want to amend what I said: games are recorded as `xml` files. I just look at the `AppData` folder and found my last games in there (seems coherent with the date of last modification). However it does not show in the stats windows for the deck. `DeckStats.xml` only contains the `warlock` game that is showing in the stats window. `DefaultDeckStats.xml` also contains three of my games (not the lasts).

I suspect the three games recorded as default are the one when the tracker failed to recognize my deck. If that is true, it lets me think that the newest versions do not properly add the information that a new game has been played in `DeckStats.xml`.

Hope you can fix this. Is there an archive of old builds?

**Comment by killjoyX** [comment]
Good question from mvy.  Would be fine to use an old build until the problem gets fixed.

**Comment by mvy** [comment]
0.6.7 woks correctly. 

@killjoyX go to the github home page, you can get older version there.

**Comment by killjoyX** [comment]
Thank you mvy, you're the best!

**Comment by Epix37** [comment]
Pretty please? 
http://www.mediafire.com/download/ue577113hu2bk02/Hearthstone_Deck_Tracker-v0.7.2_gameendfixmaybe4.zip

**Comment by Epix37** [comment]
Added an additional game-start check: http://www.mediafire.com/download/6jdtgf1vy4t6l3c/Hearthstone_Deck_Tracker-v0.7.2_gameendfixmaybe5.zip

**Comment by mvy** [comment]
Work day. I'll try later in the afternoon.

**Comment by FitzcairnHS** [comment]
I'm going to download and test the fixmaybe5 version and let you know

**Comment by FitzcairnHS** [comment]
Problem solved for me the fix5 works fine :)

**Comment by FitzcairnHS** [comment]
Hum finally i found another issue. Deck stats win/loss doesn't update anymore after a game.

**Comment by Epix37** [comment]
This might be the one: https://www.mediafire.com/?bvmx7vm3u4ryy4h

**Comment by FitzcairnHS** [comment]
Ok i'm gonna test this one

**Comment by Epix37** [comment]
note dialog popup on hearthstone start in that version is fixed with 5c2d24d

**Comment by FitzcairnHS** [comment]
Nope stil didnt update stats and last game. I also checked my last games result and the opponent is not listed and u still have the same ratio the last win didnt count on my stats.

**Comment by Epix37** [comment]
Do you have the gamemode set to record in options > other > record games?
Could you give me the tracker log of that happening?
options > other > tracker -> check show log-tab -> log tab -> save to file -> upload to www.pastebin.com

**Comment by FitzcairnHS** [comment]
I had uncheck the record games options so i will play another paty with all check and give you the log.

**Comment by FitzcairnHS** [comment]
Hum dont know why it worked this time but anyway here the log : http://pastebin.com/NvMqnJt3

Played very badly xD

**Comment by Epix37** [comment]
The "record games" options don't refer to recording a replay but to taking the game into account at all. Replay, stats, everything. So that's probably why it wouldn't work-

**Comment by FitzcairnHS** [comment]
Oh ok thanks for the info i thought the record games was only for replay so it explain why  :)

**Comment by Epix37** [comment]
So everything seems to be working fine now?

**Comment by FitzcairnHS** [comment]
Everything looks fine for me now :)

Should i delete the the official 7.1 version and keep the beta v0.7.2 tested ? I hope i wont lose my decks list if i delete the old one and install a new fresh version

**Comment by Epix37** [comment]
You can keep using the v0.7.2 and delete the v0.7.1 if you like. Data is stored in AppData so deleting what you downloaded will not delete your decks/games.

**Comment by FitzcairnHS** [comment]
Thanks a lot for your help and your amazing work ! You deserve good support for this :)

**Comment by Epix37** [comment]
Since I'm out of ideas in case this doesn't work for some reason, released v0.7.2 now. Should hopefully fix all this.

**Comment by dekow** [comment]
Nope, the decks still don't refresh between matches. I have to restart or manually disable and enable my deck.

**Comment by Epix37** [comment]
damnit... can you give me a log after such a game?
```
1) go to options > other > tracker, check "show log-tab" at the bottom
2) switch to the log- tab
3) "save to file", file will be located in [your HDT folder]/Logs

upload the file to e.g. www.pastebin.com
```

**Comment by dekow** [comment]
http://pastebin.com/z6UwrVnr

**Comment by dekow** [comment]
I seems he's unable to auto-find my deck.

**Comment by Epix37** [comment]
The decks not only don't reset at the end of a game, but not at the start of one either, right?

**Comment by dekow** [comment]
Yeah, when the new game starts I still have the used decklist from the prior game on the right side.

**Comment by Epix37** [comment]
I *think* I actually got it now! try this: http://www.mediafire.com/download/nj23v2ep2pe62ew/Hearthstone_Deck_Tracker-v0.7.3_PRE1.zip

**Comment by dekow** [comment]
Nice, thank you very much! Going to test it.

**Comment by dekow** [comment]
Works! :-D

**Comment by dekow** [comment]
The deck now resets, but doesn't count my cards properly. http://pastebin.com/nvGXiKY5

That means that I drew cards and played them, but they are still shown in my deck on the right side of the screen. This problem only occurs with this version you posted an hour ago.

**Comment by Epix37** [comment]
Ah, sorry, yes. *This* should finally be the working version: http://www.mediafire.com/download/8yelcg2vwgqqkll/Hearthstone_Deck_Tracker-v0.7.3_PRE2.zip

**Comment by dekow** [comment]
No need to say sorry. I glad you're doing something like this. ;-) Thanks testing now.

**Comment by mvy** [comment]
Works like a charm!

Good job @Epix37 !

**Comment by dekow** [comment]
Seems to work now. Thank you for your effort.

**Comment by Epix37** [comment]
Finally some good news! I'll release this as an update. Thanks for testing guys!

**Comment by surasshu** [comment]
Thanks for fixing, have a donation since I'm using your thing all the time!

**Comment by mvy** [comment]
Interesting news as well: I've just finished installing VS2013 community so I might be able to drop some line of code if I find some spare time in my agenda :)

**Comment by Epix37** [comment]
awesome :)
