### ISSUE TITLE
Export to Hearthstone doesn't work

### ISSUE THREAD

**Issue by smashpik** [Epix37/Hearthstone-Deck-Tracker#650]
i have an issue with the feature of export to HS, when i run the export it change to game window but nothing happen in it, the program works like if it was constructing the deck and finish without any notification.

**Comment by MmajestyY** [comment]
Hi ! I have absolutly the same problem. The export option just doesn't work on my PC ! But it works perfectly on my laptop. What could be the issue ? Anybody can give a hand ? Cus I am really annoyed to set up decks in the both places :S Really have no idea why it doesn't work on my PC

**Comment by Epix37** [comment]
Try if windowmode or [borderless window mode](https://www.reddit.com/r/hearthstone/comments/2oqn8t/useful_trick_to_get_borderless_fullscreen_again) has any effect.

**Comment by MmajestyY** [comment]
I already tried all windwosmode and borderless options also ALT + ENTER. Everything didn't help. What happens is when i press export to HS it swiches to heasthstone but it doesnt do anything its just waits.

**Comment by Epix37** [comment]
Could you restart the tracker, try to export a deck and then upload the "hdt_log.txt" you find in the Hearthstone Deck Tracker/Logs folder?

**Comment by MmajestyY** [comment]
[12:56:11] Helper: Checking for updates...
[12:56:11] Helper: Current version: 0.9.5.0
[12:56:12] Load: Copied log.config to C:\Users\Majesty\AppData\Local\Blizzard\Hearthstone\log.config (AlwaysOverwriteLogConfig)
[12:56:12] Game: set CurrentGameMode to None
[12:56:12] Game: Done loading card database (enUS)
[12:56:12] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[12:56:12] OpponentSecrets: Cleared secrets
[12:56:12] Tracker: Set player itemsource as playerdeck
[12:56:12] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[12:56:12] OpponentSecrets: Cleared secrets
[12:56:23] DelsectDeck: set player item source to PlayerDrawn
[12:56:23] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[12:56:23] OpponentSecrets: Cleared secrets
[12:56:30] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[12:56:30] OpponentSecrets: Cleared secrets
[12:56:30] Tracker: Set player itemsource as playerdeck
[12:56:30] Tracker: Switched to deck: U dead
[12:56:35] DeckExporter: Exporting deckname:U dead, class:Rogue, cards:30
[12:56:35] UpdateOverlay: Refreshed overlay topmost status
[12:56:35] DeckExporter: Waiting for 0 seconds before starting the export process
[12:56:35] DeckExporter: Clearing deck...
[12:56:40] UpdateOverlay: Refreshed overlay topmost status
[12:56:43] DeckExporter: Error exporting deck: Object reference not set to an instance of an object.
[12:56:44] UpdateOverlay: Refreshed overlay topmost status
[12:56:46] UpdateOverlay: Refreshed overlay topmost status
[12:56:47] Overlay: Enabled mouse hook

**Comment by MmajestyY** [comment]
Tried second time
[12:58:41] UpdateOverlay: Refreshed overlay topmost status
[12:58:44] UpdateOverlay: Refreshed overlay topmost status
[12:58:50] DeckExporter: Exporting deckname:U dead, class:Rogue, cards:30
[12:58:50] UpdateOverlay: Refreshed overlay topmost status
[12:58:50] DeckExporter: Waiting for 0 seconds before starting the export process
[12:58:50] DeckExporter: Clearing deck...
[12:58:50] DeckExporter: Setting deck name...
[12:58:51] DeckExporter: Clicking "all" crystal...
[12:58:51] DeckExporter: Creating deck...
[12:59:00] DeckExporter: Exporting aborted, window lost focus
[12:59:01] UpdateOverlay: Refreshed overlay topmost status

**Comment by MmajestyY** [comment]
It's wierd that it works perfectly on my laptop but on my pc just don't want to export :(

**Comment by Epix37** [comment]
Good thing I print the full exception there... 

Try this: 
1) close the tracker
2) rename the config.xml in `%AppData%/HearthstoneDeckTracker` to something  (e.g. to config1.xml) 
3) try exporting again

**Comment by Epix37** [comment]
If that doesn't help, see if setting a delay in `options > other > exporting` (wait X seconds before starting) does.

**Comment by MmajestyY** [comment]
Tried both. Same issue .. made it to wait 3 sec ... Still same problem 
Resetting the config also didn't work

**Comment by MmajestyY** [comment]
I don't know if its relevant to the issue but i have 1 more problem with the deck tracker on the PC . When i try to move thing around after unlock them i just can't it doesnt let me press and drag like on my laptop

**Comment by Epix37** [comment]
Hmmm... maybe try turning Aero on/off.

**Comment by MmajestyY** [comment]
I dont think i have aero at all i am on windows 8.1 On laptop i am also wind 8.1

**Comment by MmajestyY** [comment]
Sooo ... Any other solutions i can try ? :S

**Comment by Epix37** [comment]
I have a feeling it's something rather simple but I'm out of ideas at the moment :/.

**Comment by MmajestyY** [comment]
I think its related to the issue that i cant move around things when i unlock the Deck Tracker. It must be something wrong.

**Comment by Epix37** [comment]
Yea. I would guess it is some issue with the overlay being focused for some reason (which is why I thought of aero). Not sure what that tells me though. Maybe a graphics card driver issue? Try updating that if possible.

**Comment by MmajestyY** [comment]
I have GTX 770 and I am always on last drivers. Update immediately when new come so I doubt its that :(

**Comment by smashpik** [comment]
For me this issue was solved after update to the last version, now it works without any problem, i hope this info could be useful to solve the issue.

**Comment by MmajestyY** [comment]
Still have the issue . I am on last update . Had it since the begginig of using on this PC. Never had problems on my laptop so its something related to the PC
