### ISSUE TITLE
Sync from HearthStats doesn't recognize decks with multiple versions

### ISSUE THREAD

**Issue by jemiller226** [Epix37/Hearthstone-Deck-Tracker#884]
If I do a full sync from HearthStats for a deck that has a v1.0, v1.1, and v2.0, it will pull the v1.0 twice and v1.1, leaving me without the most recent version of the deck. If there's no v1.1, it just duplicates the v1.0 deck.

For decks that only have v1.0 and v1.1, everything seems fine.

**Comment by Epix37** [comment]
Might be fixed for v0.10, iirc.
Prerelease: https://github.com/Epix37/HDT-Test/releases

**Comment by jemiller226** [comment]
Sadly, it doesn't appear that's the case. See the dropdown box.

![seethedropdown](https://cloud.githubusercontent.com/assets/7871449/7080819/367270e8-df06-11e4-908e-75d12e29637e.png)

**Comment by Epix37** [comment]
I should have probably mentioned that you need to re-download the deck. Make sure you have "hearthstats > auto delete decks" turned off, or delete the "playerdecks.xml" and "deckstats.xml" in "%AppData%/HearthstoneDeckTracker" (Win+R, paste) to delete everything locally.

**Comment by jemiller226** [comment]
I had deleted the decks out of the app directly before trying the new beta release, but trying to delete the XML files is worth a shot. I closed the app, deleted the files, re-opened the app, and the decks are gone.

Plugins -> HearthStats -> Force Full Sync

Deleted nothing, hit the sync button.

Still the same for the two decks that should have a v2.0.

**Comment by Epix37** [comment]
I tried up and downloading a deck with 1.0, 1.1, 2.0, 3.0 earlier, no issues. Maybe the probem is with the deck on hearthstats, upload might have been bad.

**Comment by jemiller226** [comment]
Worth a test.

I updated my mech mage deck because I was going to anyway and then told the deck tracker to sync now. The program appeared to freeze. I right clicked on the taskbar icon and closed it.

I deleted all my decks and did a full sync again. Nothing showed up in the deck list at all. When I clicked on the Druid icon on the left nav pane, I got a crash report.

The crash report mentions being out of memory. This is very much not true--I'm at less than 35% RAM usage.

I can't paste the entire text file here because it's 763 KB and comments can't be that long here.

**Comment by jemiller226** [comment]
Restarted the computer and then the app just for kicks. Now for that deck, I have 1.0, 1.1, 1.0, and 1.0 again. The three 1.0 versions are identical.

These decks were not uploaded to HearthStats in any form. I made them in the game and then altered them directly on the website.

**Comment by Epix37** [comment]
OH, were all the decks with this issue created on hearthstats? That makes a lot more sense now. I will have a look at that.

**Comment by jemiller226** [comment]
Yes. Here's what my typical deck creation process has been up till now.

Go into game, create deck. Use HearthStats Companion to upload deck to HearthStats. Any revisions I make to the deck I do directly on the website because I have my doubts that the Companion would do versioning correctly.

Why I would love this to work is that the HearthStats Companion, for all it does well, has a number of outstanding bugs that I'm finding it harder and harder to put up with. I'd love one tool to do all my interaction with the site just the way you have set up. You seem to be much more responsive here, which is awesome.

**Comment by Epix37** [comment]
:).
This issue is fixed for the next update. Minor problem will be, that if you have 1.0, 1.1, 1.0 and sync, it will add 2.0 to the end, not replacing the 2nd 1.0. There's not much I can do about that (I think). It will work as expected though, if the deck is synced "from scratch".

**Comment by jemiller226** [comment]
Considering I haven't been using the Deck Tracker as intended just yet,
this won't be a problem.

**Comment by jemiller226** [comment]
I hate to reopen a ticket, but this is not fixed. Now, rather than not showing all versions of these decks, it doesn't sync ANY version of the deck at all. In fact, the mech mage deck I mentioned as an example isn't even in the list of decks available to be synced.

In fact, the only deck in my list that has more than one version is my mid-range druid, which has a 1.0 and a 1.1. After that, it seems to ignore every deck with multiple versions.

**Comment by Epix37** [comment]
Could be a problem with old decks on hearthstats? I just created created 3 new decks with multiple versions, synced, all there, modified all of them, all changes synced.

Could you upload the log from you trying to full sync? You can find the log in "%AppData%/HearthstoneDeckTracker/Logs". www.pastebin.com

**Comment by jemiller226** [comment]
OK. I ran a full sync and it gave me a list of decks. I pulled them all in, and then the deck list shows as empty. If I close the app and re-open it, the decks are there, although with the versioning issue I mentioned.

Pastebin here: http://pastebin.com/WtL7Tfv3

So I then deleted all the decks and tried again. Again, the same basic stuff in the log. If I click on one of the class icons while the list appears to be empty, I get an appcrash with the following info: http://pastebin.com/QBxBWeUB

**Comment by jemiller226** [comment]
And I apologize if I seem as if I'm harping. I actually work in IT, and I don't want to be a problem customer!

**Comment by Epix37** [comment]
Don't worry :).

The logs actually do help a lot though. Could you link me two or three of the decks that have missing versions (hearthstats)?

**Comment by jemiller226** [comment]
[This](http://hearthstats.net/decks/mech-mage--109?locale=en) is probably the biggest one as far as impact goes for obvious reasons.

[Another one](http://hearthstats.net/decks/face-hunter--430?locale=en).

I've been trying to avoid changing the major version number of a deck since I found this app, so those are the only two I could find quickly.

**Comment by Epix37** [comment]
A few things were fixed on the server side (I think those are live by now). Try if the syncing works for you now.

**Comment by jemiller226** [comment]
I get versioning now. Yay!

I still get the crash mentioned in the second pastebin above, but the log looks a little different now: http://pastebin.com/C7DiDBL3

Note that it tries to pull a deck with no name toward the end of the log. I'm not sure if that means anything.

**Comment by Epix37** [comment]
That crash should be fixed with v0.10.1
